"""Generate rule-based consulting recommendations from KPI outputs."""

from __future__ import annotations

from pathlib import Path

import duckdb
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DB_PATH = PROJECT_ROOT / "data" / "processed" / "nyc_311.duckdb"
OUTPUT_DIR = PROJECT_ROOT / "outputs" / "sample_dashboard_data"
INSIGHTS_DIR = PROJECT_ROOT / "outputs" / "insights"


def load_table(connection: duckdb.DuckDBPyConnection, table: str) -> pd.DataFrame:
    return connection.execute(f"SELECT * FROM {table}").df()


def generate_summary() -> Path:
    if not DB_PATH.exists():
        raise FileNotFoundError(f"DuckDB database not found: {DB_PATH}. Run src/transform_311.py first.")

    INSIGHTS_DIR.mkdir(parents=True, exist_ok=True)
    with duckdb.connect(str(DB_PATH), read_only=True) as connection:
        agency = load_table(connection, "agency_performance_kpis")
        borough = load_table(connection, "borough_service_kpis")
        complaint = load_table(connection, "complaint_type_kpis")
        backlog = load_table(connection, "backlog_kpis")
        monthly = load_table(connection, "monthly_request_kpis")
        overall = connection.execute(
            """
            SELECT
                COUNT(*) AS total_requests,
                SUM(is_open::INT) AS open_requests,
                AVG(resolution_hours) AS avg_resolution_hours,
                MEDIAN(resolution_hours) AS median_resolution_hours,
                AVG(closed_within_7d::INT) AS pct_closed_within_7d
            FROM fact_service_requests
            """
        ).df().iloc[0]

    anomalies_path = OUTPUT_DIR / "anomalies.csv"
    anomalies = pd.read_csv(anomalies_path) if anomalies_path.exists() else pd.DataFrame()

    total_requests = int(overall["total_requests"])
    open_requests = int(overall["open_requests"] or 0)
    backlog_rate = open_requests / total_requests if total_requests else 0
    avg_resolution = float(overall["avg_resolution_hours"]) if pd.notna(overall["avg_resolution_hours"]) else 0
    pct_7d = float(overall["pct_closed_within_7d"]) if pd.notna(overall["pct_closed_within_7d"]) else 0

    high_backlog = backlog.sort_values(["backlog_rate", "total_requests"], ascending=[False, False]).head(5)
    top_complaints = complaint.sort_values("total_requests", ascending=False).head(5)
    slow_agencies = agency.sort_values("avg_resolution_hours", ascending=False).head(5)
    top_borough = borough.sort_values("total_requests", ascending=False).head(1)
    latest_mom = monthly.dropna(subset=["mom_request_growth_pct"]).sort_values("request_month").tail(1)

    sample_start = None
    sample_end = None
    if not monthly.empty and "request_month" in monthly.columns:
        sample_start = str(monthly["request_month"].min())[:10]
        sample_end = str(monthly["request_month"].max())[:10]

    lines = [
        "# Executive Summary",
        "",
        "## Situation",
        "",
        "NYC service leaders need an operational view of 311 demand, backlog risk, and emerging complaint spikes. This local analytics consulting project uses public NYC Open Data to show how a client could move from raw service-request data to governed Power BI reporting and explainable AI monitoring.",
        "",
        "This report is generated by rules and templates from the KPI tables. It does not call an external LLM API.",
        "",
        "## KPI Snapshot",
        "",
        f"- Total requests analyzed: **{total_requests:,}**",
        f"- Open requests: **{open_requests:,}**",
        f"- Backlog rate: **{backlog_rate:.1%}**",
        f"- Average resolution time: **{avg_resolution:.1f} hours**",
        f"- Median resolution time: **{overall['median_resolution_hours']:.1f} hours**",
        f"- Closed within 7 days: **{pct_7d:.1%}**",
        f"- Anomalies detected: **{len(anomalies):,}**",
    ]

    if not latest_mom.empty:
        row = latest_mom.iloc[0]
        lines.append(f"- Latest month-over-month request growth: **{row['mom_request_growth_pct']:.1%}**")
    elif sample_start and sample_end:
        lines.append("- Month-over-month growth: **not available in the committed sample** because the recent 100K-record extract falls within one month.")

    lines.extend(["", "## Key Findings", ""])

    if not top_complaints.empty:
        row = top_complaints.iloc[0]
        lines.append(
            f"- **Demand concentration:** {row['complaint_type']} is the highest-volume complaint category with {int(row['total_requests']):,} requests."
        )

    if not top_borough.empty:
        row = top_borough.iloc[0]
        lines.append(
            f"- **Geographic demand:** {row['borough']} has the largest volume in the sample with {int(row['total_requests']):,} requests."
        )

    if not slow_agencies.empty:
        row = slow_agencies.iloc[0]
        if pd.notna(row["avg_resolution_hours"]):
            lines.append(
                f"- **Resolution-time exposure:** {row['agency']} has the highest average resolution time among agency KPI rows at {row['avg_resolution_hours']:.1f} hours."
            )

    if not high_backlog.empty:
        row = high_backlog.iloc[0]
        lines.append(
            f"- **Backlog concentration:** {row['agency']} / {row['borough']} shows the highest backlog rate in the current backlog table ({row['backlog_rate']:.1%}, {int(row['total_requests']):,} requests)."
        )

    if not anomalies.empty:
        row = anomalies.iloc[0]
        lines.append(
            f"- **Anomaly signal:** {row['complaint_type']} in {row['borough']} reached {int(row['total_requests']):,} requests on {row['request_date']}, above its rolling baseline."
        )

    lines.extend(["", "## Risks", ""])

    if backlog_rate >= 0.15:
        lines.append("- Elevated open-request volume could become a service backlog issue without agency-level queue triage.")
    else:
        lines.append("- Overall backlog is controlled, but pockets of agency/borough risk still require weekly monitoring.")

    lines.append("- Recent spikes may reflect seasonal demand, weather, localized service issues, or reporting changes; they should be validated with operations owners before action.")
    lines.append("- Date-order exceptions are small but should be resolved or excluded before certifying SLA metrics for executive reporting.")

    lines.extend(["", "## Recommended Actions", ""])

    if backlog_rate >= 0.15:
        lines.append(
            "- Prioritize a backlog triage sprint: the current backlog rate is elevated enough to warrant agency-level queue review, aging analysis, and short-cycle escalation rules."
        )
    else:
        lines.append(
            "- Maintain backlog controls: backlog rate is not the primary portfolio risk, but high-risk agency/borough pockets should still be reviewed weekly."
        )

    if not high_backlog.empty:
        row = high_backlog.iloc[0]
        lines.append(
            f"- Focus backlog review on **{row['agency']} / {row['borough']}**, where backlog rate is {row['backlog_rate']:.1%} across {int(row['total_requests']):,} requests."
        )

    if not top_complaints.empty:
        row = top_complaints.iloc[0]
        lines.append(
            f"- Launch a root-cause review for **{row['complaint_type']}**, the highest-volume complaint category with {int(row['total_requests']):,} requests."
        )

    if not slow_agencies.empty:
        row = slow_agencies.iloc[0]
        if pd.notna(row["avg_resolution_hours"]):
            lines.append(
                f"- Review workflow design for **{row['agency']}**, where average resolution time is {row['avg_resolution_hours']:.1f} hours."
            )

    if not top_borough.empty:
        row = top_borough.iloc[0]
        lines.append(
            f"- Use borough-level capacity planning for **{row['borough']}**, the largest demand area in the current sample."
        )

    if not anomalies.empty:
        row = anomalies.iloc[0]
        lines.append(
            f"- Investigate the latest anomaly: **{row['complaint_type']}** in **{row['borough']}** reached {int(row['total_requests']):,} requests on {row['request_date']}."
        )

    lines.extend(
        [
            "",
            "## 30-Day Plan",
            "",
            "1. **Week 1:** Validate source-field definitions, data-quality exceptions, and KPI formulas with service operations stakeholders.",
            "2. **Week 2:** Build the Power BI semantic model with certified measures for backlog, resolution time, and SLA proxies.",
            "3. **Week 3:** Pilot weekly anomaly review using borough/complaint spike outputs and define ownership for follow-up actions.",
            "4. **Week 4:** Publish an executive dashboard and operating cadence for backlog triage, agency performance review, and data-quality remediation.",
            "",
            "## Data Quality Notes",
            "",
            "- `unique_key`, `created_date`, borough normalization, non-negative resolution hours, and status normalization passed in the generated data-quality report.",
            "- The sample flagged a small number of invalid closed-date ordering records for review.",
            "- Raw and processed data files are intentionally excluded from git; outputs can be regenerated by running the pipeline.",
            "",
            "## Methodology",
            "",
            "- Ingested public NYC Open Data 311 records from Socrata dataset `erm2-nwe9`.",
            "- Modeled bronze, silver, and gold layers locally with Python, DuckDB, and SQL.",
            "- Exported Power BI-ready CSVs for a request-grain fact table, dimensions, KPI tables, and anomaly events.",
            "- Detected anomalies using transparent rolling baselines: prior 14-day rolling mean/z-score and prior 28-day IQR checks by borough and complaint type.",
            "- Produced consulting recommendations through deterministic business rules rather than an external LLM.",
        ]
    )

    output_path = INSIGHTS_DIR / "executive_summary.md"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Saved executive summary to {output_path}")
    return output_path


if __name__ == "__main__":
    generate_summary()
